language: node_js
node_js:
  - "lts/*"

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist
  repo: euclio/euclio.github.io
  target_branch: master
  skip_cleanup: true
  fqdn: acrussell.com
  on:
    branch: master
